### ISSUE TITLE
Missing strings in en_us.json for future translations.

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [JuneDeveloper/Minecraft-Vanilla-Notebook#42]
Hello!
I found out that language file (en_us.json) contains only 2 strings, but there are actually more!

All screenshots that show all strings (that I found) that need to be added in en_us.json file:
![image](https://user-images.githubusercontent.com/51203385/205479787-a3d4ca5a-81c0-4b92-b321-4b2179cb7aea.png)
![image](https://user-images.githubusercontent.com/51203385/205479790-5b9c6e1a-bcf8-4615-9ccf-7b3533cc6550.png)
![image](https://user-images.githubusercontent.com/51203385/205479793-9fea482a-4f3e-4e88-bb74-f62985606ab6.png)

**Comment by JuneDeveloper** [comment]
Fixed in latest commit on the quilt/1.19 branch
Should be included in the next update
