### ISSUE TITLE
1.19.3 support?

### ISSUE THREAD

**Issue by RoonMoonlight** [JuneDeveloper/Minecraft-Vanilla-Notebook#43]
Nice mod! Can you add 1.19.3 support as well? If it works on 1.19.3, please can you mark it as 1.19.3 compatible on Modrinth?

**Comment by RoonMoonlight** [comment]
Oh nevermind
https://github.com/JuneDeveloper/Minecraft-Vanilla-Notebook/issues/38

**Comment by JuneDeveloper** [comment]
1.19.3 Support should now become available soon.
