### ISSUE TITLE
2.0.0

### ISSUE THREAD

**Issue by Aces-and-Jacks** [JuneDeveloper/Minecraft-Vanilla-Notebook#45]
would you be able to change to tags to 1.19.3 instead of 1.19-1.19.3? 

confuses the launcher I use

**Comment by Aces-and-Jacks** [comment]
cause there's multiple but one says 1.19.2 and the other 1.19.3

**Comment by Aces-and-Jacks** [comment]
and both are 2.0.0. so I assume it's the same for different versions

**Comment by JuneDeveloper** [comment]
Should now be fixed.
