### ISSUE TITLE
crashes when I open notebook 

### ISSUE THREAD

**Issue by Aces-and-Jacks** [JuneDeveloper/Minecraft-Vanilla-Notebook#47]
https://mclo.gs/wi9OYcK

**Comment by Aces-and-Jacks** [comment]
quilt, 1.19.3, 2.0.0

**Comment by JuneDeveloper** [comment]
I believe this is because of an incompatibility with modmenu
I will work on a fix asap, but I'm not sure if modmenu is actually the cause.

Does it still crash without the mod? Or only with it?

**Comment by Aces-and-Jacks** [comment]
without https://mclo.gs/6IK2RpY

**Comment by Aces-and-Jacks** [comment]
https://mclo.gs/WhBtqPY

Cloth Config v9
Debugify
Indium
memory Leak Fix
Quilt Kotlin Libraries
Quilt Loading Screen
Quilted Fabric API
quiltgoslightlyfasterlol
Reese's Sodium Options
Remember My Txt
Sodium
Sodium Extra
Vanilla Notebook

**Comment by Aces-and-Jacks** [comment]
crashes with those mods installed. shrunk from before

**Comment by JuneDeveloper** [comment]
Weird, not 100% what's causing this, I'll have to look into it more.

I assume you've tested the pack without my mod too, if it still crashes without it, it might be a bug in Prism, since there's some issues related to ARM processors requiring a different JRE for multimc.

I will look into it further, an older version might work for you, but I'm not sure (I don't think it'd make a difference but it's worth a shot)

**Comment by Aces-and-Jacks** [comment]
I tested without your mod installed on prism. On previous versions it's worked fine.

**Comment by JuneDeveloper** [comment]
Did you use the same installation when updating? If so you might just need to delete the config files for the mod

**Comment by Aces-and-Jacks** [comment]
ill try making a fresh instance and see if that works

**Comment by Aces-and-Jacks** [comment]
...yeah it's my config, sorry for the trouble

**Comment by Aces-and-Jacks** [comment]
I thought I reset it but I guess I forgot something

**Comment by Aces-and-Jacks** [comment]
same issue again. fresh instance. turned off mod menu still happens. works otherwise without the mod

https://mclo.gs/8e01Itb

**Comment by Aces-and-Jacks** [comment]
It's probably conflicting with another mod but I'll check that later

**Comment by JuneDeveloper** [comment]
I think I see the problem now.
In your config - are presets enabled? If they are, disable them (otherwise enable them)
It's something to do with that menu, I'll look more in depth later on but since that is a fairly new and experimental feature, it probably does have some issues like this

**Comment by Aces-and-Jacks** [comment]
<img width="1136" alt="Screen Shot 2023-01-28 at 2 03 47 PM" src="https://user-images.githubusercontent.com/106651342/215286186-bb0f029c-e7dd-4b2b-b5e7-9b5cc36ce750.png">
where would that be? and what would I call it instead?

**Comment by JuneDeveloper** [comment]
that's weird, it's not there..
That would definitely explain the crash lol - the config file is old.

It needs to be identical to this, my implementation for config is very.... rudimentary.
It's one thing I want to improve in the future, but haven't gotten around to.

Make sure there's no spacing above and where this code block starts, should be line 0 in the config file:
```
# You need to reload for these to take affect!
# Directory for the pages to be stored in (e.g .minecraft/CoordinateBook)
pagedirectory=Notebook/Default
# Set page limits, negative numbers mean no limit
pagelimit=-1
# Page to start on after opening the book
startpage=0
# Presets enabled?
presets=false
```

Not sure whether the cause of this is by bug or not, but I'll look into it still

**Comment by Aces-and-Jacks** [comment]
I can try on another fresh instance and see if the config file is different. It should've been a fresh instance already but maybe the mod didn't update. Tho I'll check later today

**Comment by JuneDeveloper** [comment]
Is this safe to close? Any update?

**Comment by Aces-and-Jacks** [comment]
yeah sorry. Kinda forgot about it a bit. It works now, thanks for the help

**Comment by Aces-and-Jacks** [comment]
did another fresh instance. I think I just copy pasted before and forgot to update before starting up minecraft. this time I made sure that the mod was updated and started minecraft up. works all good now
