### ISSUE TITLE
Version isn´t right...

### ISSUE THREAD

**Issue by DaPiCu** [JuneDeveloper/Minecraft-Vanilla-Notebook#48]
![Screenshot_1](https://user-images.githubusercontent.com/95594190/216660212-9c5b251e-ae51-4dd2-98f5-1126088f36e2.png)
![Screenshot_2](https://user-images.githubusercontent.com/95594190/216660213-8bdf7f11-494e-459b-a8ec-39c300c8862a.png)
I downloaded version 1.19-1.19.3 on Modrinth (screenshot 2)  but the error message (screenshot 1) says it is not compatible with 1.19.2.

**Comment by JuneDeveloper** [comment]
I have updated the modrinth page to be 1.19.3 exclusively. 
It might take a couple hours to update though
