### ISSUE TITLE
Mod button overlap with Figura in pause menu

### ISSUE THREAD

**Issue by Aces-and-Jacks** [JuneDeveloper/Minecraft-Vanilla-Notebook#50]
Your mod overlaps the figura mod's button. Not sure if I should go to you or Figura about it. Or if possible some way for me to change the location

**Comment by JuneDeveloper** [comment]
I can quite easily change the location of the button - but the problem would still be there just moved on to a solution I'd still need to fix later.

I'll look into what I can do, might make it toggleable via config (You can access the book via a keybind anyway)

**Comment by Aces-and-Jacks** [comment]
Would it be possible to make it change position if another mod occupies that area? Or since it's another mod and not part of vanilla books it'd be impossible to do that

**Comment by JuneDeveloper** [comment]
I could check if a specific mod is installed and change it - but it's quite hard to set a specific placement because quite a few mods use buttons in that vague area, so it might just end up overlapping with another mod.
I could allow the user to set their own x/y position on the screen, but that's quite a lot of manual configuring for such a simple mod.

**Comment by Aces-and-Jacks** [comment]
well it isn't much of a big issue just an inconvenience. If you end up not wanting to fix it I'd understand

**Comment by JuneDeveloper** [comment]
This is definitely something I want to try and fix, I'll probably make a config file for it where you can either change the position, or just disable them completely.

**Comment by Aces-and-Jacks** [comment]
by disabling do you mean not showing the button in the pause menu?

**Comment by Aces-and-Jacks** [comment]
yeah, I don't really use the key bind option so changing the position would be helpful

**Comment by JuneDeveloper** [comment]
I am hoping to fit this into the next update in the works, 2.1.1, alongside bugfixes.
I'll add more in-depth config for the buttons in 2.1.1, and in the future I will add a proper UI for it (Like the current one, but for buttons)

I did have an idea for buttons configurable via json or similar so maybe it's time to revive that concept lol.

**Comment by JuneDeveloper** [comment]
This issue is now fixed in the release candidate on my discord server, I'm hoping to release it to the public soon, just want to make some minor tweaks before then.
I'll close this issue for now.
