### ISSUE TITLE
Can't enter down in notebook

### ISSUE THREAD

**Issue by Player505** [JuneDeveloper/Minecraft-Vanilla-Notebook#53]
Can't enter down on notebook to create new line

**Comment by JuneDeveloper** [comment]
Sorry for the long wait in the reply, but this is something I meant to fix a long time ago and would appear to have forgotten about.

I will implement it with the next major version, should come out sometime soon hopefully.

**Comment by JuneDeveloper** [comment]
I will have to fix this in the future, im not sure if i can get it ready for next update
