### ISSUE TITLE
the enter "W" bug

### ISSUE THREAD

**Issue by Konijnebeer** [JuneDeveloper/Minecraft-Vanilla-Notebook#55]
as the other Issue got deleted i will put it here than
As its quite a anoying bug maybe its good to put it on the Modrinth page that 1.19.2 has this bug?
as having a broken version up is quite frustrating for users 
hope i dont come of rude, as that realy isnt my intetion :)

**Comment by JuneDeveloper** [comment]
The 1.19.2 version is currently not up to date, it will have bugs; once I get around to updaing the 1.19.2/1.19.1/1.19 versions for parity with .3, it'll be fixed across all 3, but first i need to fix bugs in .3 so they aren't going to be a nuisance to fix across all versions after the fact.

I will add a notice to the modrinth page, but this will eventually be fixed.
