### ISSUE TITLE
Crashes while opening

### ISSUE THREAD

**Issue by xetsiv** [JuneDeveloper/Minecraft-Vanilla-Notebook#60]
https://mclo.gs/sTIHQqw

**Comment by JuneDeveloper** [comment]
Are you using the right version for v2.2.0? The jar for 1.19.4 is different to the 1.19.2/1.19.1/1.19 and 1.19.3 jars - [link to the 1.19.4 jar](https://modrinth.com/mod/notebook/version/A2LH2kdM).
Let me know if the issue persists. You might also want to try deleting the mod's config files.
