### ISSUE TITLE
How do I access the notebook? Broken by update? 

### ISSUE THREAD

**Issue by Mat-a-tat** [JuneDeveloper/Minecraft-Vanilla-Notebook#62]
Howdy! I might just be silly; but I can't seem to access the notebook anywhere. I couldn't find any documentation or images of where it's accessed (just what it's like in use.) This might however be related to my version (3.0.0) 

Update! Did find it on the title screen. However, I still don't see how this can be accessed in game (in solo worlds atleast) and do think having this location pointed out somewhere on here would be lovely.

**Comment by JuneDeveloper** [comment]
There's a key bind for it - The button will return at some point in the future. Just temporarily gone.
