### ISSUE TITLE
Pressing space key activating GUI buttons instead of writing a space.

### ISSUE THREAD

**Issue by static2601** [JuneDeveloper/Minecraft-Vanilla-Notebook#64]
If I added a page or went to a page, pressing space will activate the GUI button last pressed instead of adding a space in the text I'm writing. I have to click the up/down arrow at the top left of the screen to put the cursor back on the page. Seems like this would be an easy fix by just refocusing the text field after a button is pressed.
Edit: this is for Minecraft v1.20 using Fabric. version 3.0.0 of the notebook mod

**Comment by JuneDeveloper** [comment]
Yeah, this is an issue with 1.20+ when using the arrow keys. 
I noticed it in development but it's proving quite difficult to fix, I'm not 100% sure how to override the game's default behaviour.

Hopefully will be fixed soon, just depends how long it takes for me to figure out what part of Minecraft's code controls the button highlighting.

**Comment by JuneDeveloper** [comment]
Fixed in this latest commit, not the best fix but a fix nonetheless
